version: '3'
services:
  parse:
    build:
      context: .
    image: autoria
    volumes:
      - .:/app
    env_file: .env
    restart: always
  db:
    image: postgres
    ports:
      - "54322:5432"
    environment:
      POSTGRES_PASSWORD: 'admin123'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'postgres'
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d